stages:
  - quality-assurance
  - deploy

# Cache pip
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip

linters:
  image: python:3.9
  stage: quality-assurance
  before_script:
    - pip install tox
  script:
    - tox -e linters

  # Be nice to new contributors, but please use `tox` before commit
  allow_failure: true

deploy:
  image: python:3.9
  stage: deploy
  before_script:
    - pip install build twine
  script:
    - python -m build
    - TWINE_PASSWORD=${PIPY_TOKEN} TWINE_USERNAME=__token__ python -m twine upload --repository pypi dist/*
  only:
    refs:
      - tags
